### ISSUE TITLE
GPIO17/P1-11/0 Throwing False:: 'A pin must be specified'

### ISSUE THREAD

**Issue by emirii** [tralves/raspi-soft-pwm#6]
On Raspberry Pi 3 B, using GPIO17 (P1-11) using raspi-io/johnny-five. It looks like raspi-io-core sends an int 0 to raspi-soft-pwm.

raspi-soft-pwm checks on index.js line 65-67:
```
    if (!pin) {
      throw new Error('A pin must be specified');
    }
```
obviously 0 is false, so the error is thrown.  When I switch the check to something like this (subjective, as I'm not sure what would be sent if a pin actually wasn't specified) everything works dandy:
```
    if (pin === undefined) {
      throw new Error('A pin must be specified');
    }
```
possibly `pin === false` might work too.

**Comment by tralves** [comment]
Oh you're right! Thanks for the bug report
Fixed in 98bfdce3a23824f5f0474a2d4d69ce975d0f3515, v2.0.2

Happy codings!
